# Generated by Django 3.2 on 2021-05-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210520_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='User',
        ),
    ]
