# Generated by Django 3.2 on 2021-05-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todoitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
