# Generated by Django 3.2 on 2021-05-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todoitem_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ('-id',)},
        ),
    ]
